//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Abstract:&lt;/b&gt;.
        /// </summary>
        internal static string Abstract {
            get {
                return ResourceManager.GetString("Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open RDIMS document.  Make sure you answer \&quot;Yes\&quot; when prompted to run un-signed ActiveX.  If you did answer \&quot;Yes\&quot; and you are still getting this error message, contact TriNet Solutions at 995-0000.  If you answered \&quot;No\&quot; by mistake, refresh the page to get prompted again..
        /// </summary>
        internal static string activeXerror {
            get {
                return ResourceManager.GetString("activeXerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string advanced {
            get {
                return ResourceManager.GetString("advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        internal static string advancedsearch {
            get {
                return ResourceManager.GetString("advancedsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query-recherche-eng.aspx?t=a.
        /// </summary>
        internal static string advancedsearchlink {
            get {
                return ResourceManager.GetString("advancedsearchlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;All.
        /// </summary>
        internal static string all2 {
            get {
                return ResourceManager.GetString("all2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All File Formats.
        /// </summary>
        internal static string allFormat {
            get {
                return ResourceManager.GetString("allFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All words.
        /// </summary>
        internal static string allWords {
            get {
                return ResourceManager.GetString("allWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department of Finance - Government of Canada.
        /// </summary>
        internal static string altgocdeptimg {
            get {
                return ResourceManager.GetString("altgocdeptimg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;AND&amp;nbsp;.
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Language.
        /// </summary>
        internal static string AnyLanguage {
            get {
                return ResourceManager.GetString("AnyLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any word.
        /// </summary>
        internal static string anyWord {
            get {
                return ResourceManager.GetString("anyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string basic {
            get {
                return ResourceManager.GetString("basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Search.
        /// </summary>
        internal static string basicsearch {
            get {
                return ResourceManager.GetString("basicsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query-recherche-eng.aspx?t=b.
        /// </summary>
        internal static string basicsearchlink {
            get {
                return ResourceManager.GetString("basicsearchlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of the best 300 documents.
        /// </summary>
        internal static string best300 {
            get {
                return ResourceManager.GetString("best300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&lt;abbr title=&quot;Four digits year&quot;&gt;yyyy&lt;/abbr&gt;-&lt;abbr title=&quot;Two digits month&quot;&gt;mm&lt;/abbr&gt;-&lt;abbr title=&quot;Two digits day&quot;&gt;dd&lt;/abbr&gt;).
        /// </summary>
        internal static string blankdate {
            get {
                return ResourceManager.GetString("blankdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogs.
        /// </summary>
        internal static string blogs {
            get {
                return ResourceManager.GetString("blogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        internal static string bookmarks {
            get {
                return ResourceManager.GetString("bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        internal static string branches {
            get {
                return ResourceManager.GetString("branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By GCconnex:.
        /// </summary>
        internal static string bygcconnex {
            get {
                return ResourceManager.GetString("bygcconnex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By GCpedia:.
        /// </summary>
        internal static string bygcpedia {
            get {
                return ResourceManager.GetString("bygcpedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;By source:.
        /// </summary>
        internal static string bysource {
            get {
                return ResourceManager.GetString("bysource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calendar-en.js.
        /// </summary>
        internal static string calendar {
            get {
                return ResourceManager.GetString("calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;Canada Site.
        /// </summary>
        internal static string canadaSite {
            get {
                return ResourceManager.GetString("canadaSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Clear].
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string colon {
            get {
                return ResourceManager.GetString("colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In development.
        /// </summary>
        internal static string comingsoon {
            get {
                return ResourceManager.GetString("comingsoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string comments {
            get {
                return ResourceManager.GetString("comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;Committees.
        /// </summary>
        internal static string committees {
            get {
                return ResourceManager.GetString("committees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string contactUs {
            get {
                return ResourceManager.GetString("contactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Containing:.
        /// </summary>
        internal static string containing {
            get {
                return ResourceManager.GetString("containing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Notice, Official Languages Notice, Hyperlinking Notice, Copyright Notice.
        /// </summary>
        internal static string copyRight {
            get {
                return ResourceManager.GetString("copyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Tools.
        /// </summary>
        internal static string corporateTools {
            get {
                return ResourceManager.GetString("corporateTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents .
        /// </summary>
        internal static string countMsg1 {
            get {
                return ResourceManager.GetString("countMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string countMsg2 {
            get {
                return ResourceManager.GetString("countMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of the best .
        /// </summary>
        internal static string countMsg3 {
            get {
                return ResourceManager.GetString("countMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of .
        /// </summary>
        internal static string countMsg4 {
            get {
                return ResourceManager.GetString("countMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to documents.
        /// </summary>
        internal static string countMsg5 {
            get {
                return ResourceManager.GetString("countMsg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government of Canada, Treasury Board of Canada, Secretariat, Treasury Board of Canada Secretariat.
        /// </summary>
        internal static string creator {
            get {
                return ResourceManager.GetString("creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Page.
        /// </summary>
        internal static string currentPage {
            get {
                return ResourceManager.GetString("currentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created:.
        /// </summary>
        internal static string dateCreated {
            get {
                return ResourceManager.GetString("dateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (yyyy)([-/])(mm)([-/])(dd).
        /// </summary>
        internal static string dateFormatPattern {
            get {
                return ResourceManager.GetString("dateFormatPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated:.
        /// </summary>
        internal static string dateLastUpdated {
            get {
                return ResourceManager.GetString("dateLastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Modified:.
        /// </summary>
        internal static string dateModified {
            get {
                return ResourceManager.GetString("dateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date published:.
        /// </summary>
        internal static string datePublished {
            get {
                return ResourceManager.GetString("datePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date range.
        /// </summary>
        internal static string daterange {
            get {
                return ResourceManager.GetString("daterange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Reviewed:.
        /// </summary>
        internal static string dateReviewed {
            get {
                return ResourceManager.GetString("dateReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you mean .
        /// </summary>
        internal static string didyoumean {
            get {
                return ResourceManager.GetString("didyoumean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion.
        /// </summary>
        internal static string discussion {
            get {
                return ResourceManager.GetString("discussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display options.
        /// </summary>
        internal static string displayOptions {
            get {
                return ResourceManager.GetString("displayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Date: &lt;/strong&gt;.
        /// </summary>
        internal static string documentDate {
            get {
                return ResourceManager.GetString("documentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to that match your search..
        /// </summary>
        internal static string documentsFound {
            get {
                return ResourceManager.GetString("documentsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doing Research.
        /// </summary>
        internal static string doingResearch {
            get {
                return ResourceManager.GetString("doingResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Resources.
        /// </summary>
        internal static string employeeResources {
            get {
                return ResourceManager.GetString("employeeResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        internal static string employees {
            get {
                return ResourceManager.GetString("employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string enterprisesearch {
            get {
                return ResourceManager.GetString("enterprisesearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        internal static string enterprisesearcha {
            get {
                return ResourceManager.GetString("enterprisesearcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Search.
        /// </summary>
        internal static string enterprisesearchb {
            get {
                return ResourceManager.GetString("enterprisesearchb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entire document.
        /// </summary>
        internal static string entiredoc {
            get {
                return ResourceManager.GetString("entiredoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please don&apos;t change the parameters in the URL..
        /// </summary>
        internal static string errorDontPlayWithURL {
            get {
                return ResourceManager.GetString("errorDontPlayWithURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;To&apos; date must be greater than &apos;From&apos; date.  .
        /// </summary>
        internal static string errorEndDateMustBeSmallerThanStartDate {
            get {
                return ResourceManager.GetString("errorEndDateMustBeSmallerThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &apos;To&apos; date in date range..
        /// </summary>
        internal static string errorInvalidEndDate {
            get {
                return ResourceManager.GetString("errorInvalidEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &apos;From&apos; date in date range..
        /// </summary>
        internal static string errorInvalidStartDate {
            get {
                return ResourceManager.GetString("errorInvalidStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;H5&gt;There was an error in your query.  Please check your query and try again.&lt;/H5&gt;.
        /// </summary>
        internal static string errorMessage {
            get {
                return ResourceManager.GetString("errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify at least 3 characters with a wild card character.  .
        /// </summary>
        internal static string errorThreeCharWithWild {
            get {
                return ResourceManager.GetString("errorThreeCharWithWild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Please enter a value in the Search field before clicking the Search button..
        /// </summary>
        internal static string errorYouMustEnterQuery {
            get {
                return ResourceManager.GetString("errorYouMustEnterQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string events {
            get {
                return ResourceManager.GetString("events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Format.
        /// </summary>
        internal static string FileFormat {
            get {
                return ResourceManager.GetString("FileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*) Some documents may be found under multiple file formats, e.g. an email message containing a PDF attachment may be classified under both Outlook and PDF..
        /// </summary>
        internal static string fileFormatHelp {
            get {
                return ResourceManager.GetString("fileFormatHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the requested file is too long.  Please contact TriNet Solutions at 995-0000 for more information..
        /// </summary>
        internal static string filePathTooLong {
            get {
                return ResourceManager.GetString("filePathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter your results&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;.
        /// </summary>
        internal static string filterResults {
            get {
                return ResourceManager.GetString("filterResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department of Finance.
        /// </summary>
        internal static string financeDepartment {
            get {
                return ResourceManager.GetString("financeDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBS Search.
        /// </summary>
        internal static string FIN_toggle {
            get {
                return ResourceManager.GetString("FIN_toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBS.
        /// </summary>
        internal static string FIN_toggleAcronym {
            get {
                return ResourceManager.GetString("FIN_toggleAcronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  first.
        /// </summary>
        internal static string first {
            get {
                return ResourceManager.GetString("first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Page of Results.
        /// </summary>
        internal static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Page.
        /// </summary>
        internal static string firstResultsPage {
            get {
                return ResourceManager.GetString("firstResultsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        internal static string forums {
            get {
                return ResourceManager.GetString("forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four digits year.
        /// </summary>
        internal static string fourDigitYear {
            get {
                return ResourceManager.GetString("fourDigitYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCIntranet-en_frontend.
        /// </summary>
        internal static string frontEnd {
            get {
                return ResourceManager.GetString("frontEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Text.
        /// </summary>
        internal static string ft {
            get {
                return ResourceManager.GetString("ft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;GCconnex:&lt;/h4&gt;.
        /// </summary>
        internal static string gcconnex {
            get {
                return ResourceManager.GetString("gcconnex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCconnex-en_frontend.
        /// </summary>
        internal static string GCconnexfrontEnd {
            get {
                return ResourceManager.GetString("GCconnexfrontEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GC Departments &amp; Agencies.
        /// </summary>
        internal static string gcDepartmentsAgencies {
            get {
                return ResourceManager.GetString("gcDepartmentsAgencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;GCdirectory:&lt;/h2&gt;.
        /// </summary>
        internal static string gcdirectory {
            get {
                return ResourceManager.GetString("gcdirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;GCdirectory.
        /// </summary>
        internal static string gcdirectory2 {
            get {
                return ResourceManager.GetString("gcdirectory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCdGCdirectoryEn_frontend.
        /// </summary>
        internal static string GCdirectoryfrontEnd {
            get {
                return ResourceManager.GetString("GCdirectoryfrontEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCIntranet-en_frontend.
        /// </summary>
        internal static string GCintranetfrontEnd {
            get {
                return ResourceManager.GetString("GCintranetfrontEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;GCpedia:&lt;/h4&gt;.
        /// </summary>
        internal static string gcpedia {
            get {
                return ResourceManager.GetString("gcpedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;GCpedia.
        /// </summary>
        internal static string gcpedia2 {
            get {
                return ResourceManager.GetString("gcpedia2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCpedia-en_frontend.
        /// </summary>
        internal static string GCpediafrontEnd {
            get {
                return ResourceManager.GetString("GCpediafrontEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GC sites.
        /// </summary>
        internal static string gcsites {
            get {
                return ResourceManager.GetString("gcsites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government of Canada.
        /// </summary>
        internal static string goc {
            get {
                return ResourceManager.GetString("goc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/InfoSite/phase1/images/fin/goc-dept_e.gif.
        /// </summary>
        internal static string gocdeptimg {
            get {
                return ResourceManager.GetString("gocdeptimg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goc Sites.
        /// </summary>
        internal static string gocsites {
            get {
                return ResourceManager.GetString("gocsites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Top of Page.
        /// </summary>
        internal static string goToTopOfPage {
            get {
                return ResourceManager.GetString("goToTopOfPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string groups {
            get {
                return ResourceManager.GetString("groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lang_en.
        /// </summary>
        internal static string GSALang {
            get {
                return ResourceManager.GetString("GSALang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://intranet.canada.ca/index-eng.asp.
        /// </summary>
        internal static string homepage {
            get {
                return ResourceManager.GetString("homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideas.
        /// </summary>
        internal static string ideas {
            get {
                return ResourceManager.GetString("ideas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Notices.
        /// </summary>
        internal static string importantNotices {
            get {
                return ResourceManager.GetString("importantNotices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Management and Technology.
        /// </summary>
        internal static string imt {
            get {
                return ResourceManager.GetString("imt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPSA intranet and Infosite.
        /// </summary>
        internal static string infositecsb {
            get {
                return ResourceManager.GetString("infositecsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infosite.
        /// </summary>
        internal static string infositefin {
            get {
                return ResourceManager.GetString("infositefin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infosite.
        /// </summary>
        internal static string infositehome {
            get {
                return ResourceManager.GetString("infositehome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPSA internet site.
        /// </summary>
        internal static string internetcpsa {
            get {
                return ResourceManager.GetString("internetcpsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIN internet site.
        /// </summary>
        internal static string internetfinorcsb {
            get {
                return ResourceManager.GetString("internetfinorcsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBS internet site.
        /// </summary>
        internal static string internettbs {
            get {
                return ResourceManager.GetString("internettbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i&gt;Error: Your query has an invalid date or date format (must be YYYY-MM-DD).&lt;/i&gt; Try changing your query term(s) and submitting the search again. If you suspect a problem with the search, please report this error. 
        ///.
        /// </summary>
        internal static string inValidDate {
            get {
                return ResourceManager.GetString("inValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date range.
        /// </summary>
        internal static string inValidDateRange {
            get {
                return ResourceManager.GetString("inValidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string keywordContents {
            get {
                return ResourceManager.GetString("keywordContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageField {
            get {
                return ResourceManager.GetString("LanguageField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string languageID {
            get {
                return ResourceManager.GetString("languageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eng.
        /// </summary>
        internal static string languageSuffix {
            get {
                return ResourceManager.GetString("languageSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified:.
        /// </summary>
        internal static string lastModified {
            get {
                return ResourceManager.GetString("lastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Page of Results.
        /// </summary>
        internal static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string links {
            get {
                return ResourceManager.GetString("links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string members {
            get {
                return ResourceManager.GetString("members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find what you&apos;re looking for? View this search on .
        /// </summary>
        internal static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mime-Type:.
        /// </summary>
        internal static string mimetype {
            get {
                return ResourceManager.GetString("mimetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Drives.
        /// </summary>
        internal static string networkdrives {
            get {
                return ResourceManager.GetString("networkdrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Room.
        /// </summary>
        internal static string newsRoom {
            get {
                return ResourceManager.GetString("newsRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page of Results.
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        internal static string nextResultsPage {
            get {
                return ResourceManager.GetString("nextResultsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No documents matched the query..
        /// </summary>
        internal static string noDocuments {
            get {
                return ResourceManager.GetString("noDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No documents were found to match your query.
        /// </summary>
        internal static string noResults {
            get {
                return ResourceManager.GetString("noResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username hasn&apos;t been found in the database.  Please contact TriNet Solutions at 995-0000 for more information..
        /// </summary>
        internal static string NotFoundInDB {
            get {
                return ResourceManager.GetString("NotFoundInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notices.
        /// </summary>
        internal static string notices {
            get {
                return ResourceManager.GetString("notices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Title.
        /// </summary>
        internal static string noTitle {
            get {
                return ResourceManager.GetString("noTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On:.
        /// </summary>
        internal static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        internal static string openFolder {
            get {
                return ResourceManager.GetString("openFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;OR&amp;nbsp;.
        /// </summary>
        internal static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string organization {
            get {
                return ResourceManager.GetString("organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 412 px.
        /// </summary>
        internal static string padding {
            get {
                return ResourceManager.GetString("padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string pageLabel {
            get {
                return ResourceManager.GetString("pageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        internal static string pages {
            get {
                return ResourceManager.GetString("pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string para_category {
            get {
                return ResourceManager.GetString("para_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string para_subject {
            get {
                return ResourceManager.GetString("para_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        internal static string para_type {
            get {
                return ResourceManager.GetString("para_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Book.
        /// </summary>
        internal static string phoneBook {
            get {
                return ResourceManager.GetString("phoneBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        internal static string photos {
            get {
                return ResourceManager.GetString("photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polls.
        /// </summary>
        internal static string polls {
            get {
                return ResourceManager.GetString("polls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string premiers {
            get {
                return ResourceManager.GetString("premiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page of Results.
        /// </summary>
        internal static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        internal static string previousResultsPage {
            get {
                return ResourceManager.GetString("previousResultsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Version.
        /// </summary>
        internal static string printVersion {
            get {
                return ResourceManager.GetString("printVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Service Human Resources Management Agency of Canada.
        /// </summary>
        internal static string psadept {
            get {
                return ResourceManager.GetString("psadept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publiservice Site.
        /// </summary>
        internal static string publiserviceSite {
            get {
                return ResourceManager.GetString("publiserviceSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Query:&lt;/b&gt;&amp;nbsp;.
        /// </summary>
        internal static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDIMS.
        /// </summary>
        internal static string rdims {
            get {
                return ResourceManager.GetString("rdims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDIMS.
        /// </summary>
        internal static string RDIMS_TBSSCT {
            get {
                return ResourceManager.GetString("RDIMS_TBSSCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refine by.
        /// </summary>
        internal static string refine {
            get {
                return ResourceManager.GetString("refine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refine Search.
        /// </summary>
        internal static string refineSearch {
            get {
                return ResourceManager.GetString("refineSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Links.
        /// </summary>
        internal static string relatedLinks {
            get {
                return ResourceManager.GetString("relatedLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevancy.
        /// </summary>
        internal static string Relevancy {
            get {
                return ResourceManager.GetString("Relevancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository:.
        /// </summary>
        internal static string Repository {
            get {
                return ResourceManager.GetString("Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research.
        /// </summary>
        internal static string research {
            get {
                return ResourceManager.GetString("research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset filters.
        /// </summary>
        internal static string resetFilters {
            get {
                return ResourceManager.GetString("resetFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string ResultPage {
            get {
                return ResourceManager.GetString("ResultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string ResultPage2 {
            get {
                return ResourceManager.GetString("ResultPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ResultPage3 {
            get {
                return ResourceManager.GetString("ResultPage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing results&amp;nbsp;.
        /// </summary>
        internal static string results {
            get {
                return ResourceManager.GetString("results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results per page.
        /// </summary>
        internal static string ResultsPerPage {
            get {
                return ResourceManager.GetString("ResultsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to.
        /// </summary>
        internal static string returnTo {
            get {
                return ResourceManager.GetString("returnTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query-recherche-eng.aspx.
        /// </summary>
        internal static string searchAction {
            get {
                return ResourceManager.GetString("searchAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query-recherche2-eng.aspx.
        /// </summary>
        internal static string searchAction2 {
            get {
                return ResourceManager.GetString("searchAction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query-rechercheTest-eng.aspx.
        /// </summary>
        internal static string searchAction3 {
            get {
                return ResourceManager.GetString("searchAction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query-rechercheTest-eng.aspx.
        /// </summary>
        internal static string searchActionTest {
            get {
                return ResourceManager.GetString("searchActionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Search Criteria: &lt;/b&gt;.
        /// </summary>
        internal static string searchCriteria {
            get {
                return ResourceManager.GetString("searchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.  Please try again. Your query may be too vague and take too long to return.  If the error persists, please contact TriNet Solutions at 995-0000..
        /// </summary>
        internal static string SearchError {
            get {
                return ResourceManager.GetString("SearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All terms were invalid, too short, too common, or incorrectly formatted. Try changing your query term(s) and submitting the search again.  If you suspect a problem with the search, please report this error to TriNet Solutions at 995-0000..
        /// </summary>
        internal static string SearchErrorStopWords {
            get {
                return ResourceManager.GetString("SearchErrorStopWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://intradev/infosite/search/es_faq-e.asp.
        /// </summary>
        internal static string searchfaqlink {
            get {
                return ResourceManager.GetString("searchfaqlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search For.
        /// </summary>
        internal static string searchfor {
            get {
                return ResourceManager.GetString("searchfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Help.
        /// </summary>
        internal static string searchhelp {
            get {
                return ResourceManager.GetString("searchhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /search-recherche/cmn/help-aide-eng.asp.
        /// </summary>
        internal static string searchhelplink_internet {
            get {
                return ResourceManager.GetString("searchhelplink_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://intradev/infosite/search/es_help-e.asp.
        /// </summary>
        internal static string searchhelplink_intranet {
            get {
                return ResourceManager.GetString("searchhelplink_intranet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In:.
        /// </summary>
        internal static string searchin {
            get {
                return ResourceManager.GetString("searchin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search now.
        /// </summary>
        internal static string searchNow {
            get {
                return ResourceManager.GetString("searchNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        internal static string searchRes {
            get {
                return ResourceManager.GetString("searchRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;H2&gt;Search Results&lt;/H2&gt;.
        /// </summary>
        internal static string searchResults {
            get {
                return ResourceManager.GetString("searchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search intranet.canada.ca.
        /// </summary>
        internal static string searchSite {
            get {
                return ResourceManager.GetString("searchSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search terms used: .
        /// </summary>
        internal static string searchTermsUsed {
            get {
                return ResourceManager.GetString("searchTermsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Search type: &lt;/b&gt;.
        /// </summary>
        internal static string searchType {
            get {
                return ResourceManager.GetString("searchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site:.
        /// </summary>
        internal static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip all menus.
        /// </summary>
        internal static string skipAllMenus {
            get {
                return ResourceManager.GetString("skipAllMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip first menu.
        /// </summary>
        internal static string skipFirstMenu {
            get {
                return ResourceManager.GetString("skipFirstMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to search results.
        /// </summary>
        internal static string skipSearchNav {
            get {
                return ResourceManager.GetString("skipSearchNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Sort by:&lt;/strong&gt;.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        internal static string source {
            get {
                return ResourceManager.GetString("source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government of Canada, Treasury Board of Canada Secretariat.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Management and Technology.
        /// </summary>
        internal static string subjectCategory {
            get {
                return ResourceManager.GetString("subjectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Repository:.
        /// </summary>
        internal static string subrepository {
            get {
                return ResourceManager.GetString("subrepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talks.
        /// </summary>
        internal static string talks {
            get {
                return ResourceManager.GetString("talks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasury Board of Canada Secretariat.
        /// </summary>
        internal static string TBS {
            get {
                return ResourceManager.GetString("TBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index-fra.asp.
        /// </summary>
        internal static string tbsWebToggle {
            get {
                return ResourceManager.GetString("tbsWebToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance Search.
        /// </summary>
        internal static string TBS_toggle {
            get {
                return ResourceManager.GetString("TBS_toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIN.
        /// </summary>
        internal static string TBS_toggleAcronym {
            get {
                return ResourceManager.GetString("TBS_toggleAcronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string template {
            get {
                return ResourceManager.GetString("template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Phrase.
        /// </summary>
        internal static string thisPhrase {
            get {
                return ResourceManager.GetString("thisPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string titletag {
            get {
                return ResourceManager.GetString("titletag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title, keywords and description.
        /// </summary>
        internal static string tkd {
            get {
                return ResourceManager.GetString("tkd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title, keywords, description and Full text.
        /// </summary>
        internal static string tkdft {
            get {
                return ResourceManager.GetString("tkdft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string top {
            get {
                return ResourceManager.GetString("top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top of Page.
        /// </summary>
        internal static string topOfPage {
            get {
                return ResourceManager.GetString("topOfPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please .
        /// </summary>
        internal static string tryAgain1 {
            get {
                return ResourceManager.GetString("tryAgain1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  again..
        /// </summary>
        internal static string tryAgain2 {
            get {
                return ResourceManager.GetString("tryAgain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search For.
        /// </summary>
        internal static string typeQuery {
            get {
                return ResourceManager.GetString("typeQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        internal static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirepost.
        /// </summary>
        internal static string wirepost {
            get {
                return ResourceManager.GetString("wirepost", resourceCulture);
            }
        }
    }
}
